from __future__ import annotations
"""
Ad Diagnosis Workflow

Collects advertising and inventory data for one or more ASINs, then runs
an LLM-powered diagnostic to identify issues and produce prioritised recommendations.

Data sources (all run in parallel within each EnrichStep):
  - Amazon Ads API v3  : campaigns, ad groups, keywords, performance report
  - SP-API             : FBA inventory
  - SP-API Catalog     : product metadata
  - Xiyouzhaoci        : organic keyword rankings (ad traffic ratio)

Diagnostic dimensions:
  - Budget adequacy        (daily budget vs actual spend)
  - Bid competitiveness    (keyword bids vs recommended)
  - Bidding strategy       (AUTO vs MANUAL, placement adjustments, actual placement ACOS)
  - Keyword health         (high-ACOS, low-impression, missing keywords)
  - Organic keyword rank   (xiyou positions vs ad coverage)
  - Inventory risk         (available days < threshold)
  - ACOS & profitability   (per-campaign and account-level)

Input items shape:
  {"asin": "B0FXFGMD7Z"}          # minimum
  {"asin": "B0FXFGMD7Z", "sku": "SKU-001", "cogs": 8.5, "price": 24.99}

Config keys (with defaults):
  store_id                str   "US"
  region                  str   "NA"
  days                    int   30       report lookback days
  inventory_risk_days     int   30       flag if available < this many days
  acos_warn_threshold     float 0.30     warn if campaign ACOS > 30%
  acos_crit_threshold     float 0.50     critical if campaign ACOS > 50%
  budget_exhaustion_pct   float 0.90     flag if spend/budget > 90%
  enable_xiyou            bool  True     fetch organic rankings from xiyouzhaoci
  rank_lookback_months    int   6        organic rank history depth (max 24 calendar months)
                                         covariate_series extends to match this window for ITS alignment
  enable_causal_analysis  bool  True     run ITS / CausalImpact / DML on change events
  causal_metric           str   "orders" metric to model: orders | acos | clicks | spend
"""

import asyncio
import logging
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo
from typing import Any, Dict, List, Optional

from src.workflows.registry import WorkflowRegistry
from src.workflows.engine import Workflow, WorkflowContext
from src.workflows.steps.enrich import EnrichStep
from src.workflows.steps.process import ProcessStep
from src.workflows.steps.base import ComputeTarget
from src.intelligence.processors.causal_analysis import ATTR_PRE_START, ATTR_POST_END
from src.core.data_cache import data_cache as _data_cache

logger = logging.getLogger(__name__)

# ── Cache keys (shared across per-item enrichers to avoid duplicate API calls) ──
_KEY_CAMPAIGNS        = "ad_diag:campaigns"
_KEY_PERFORMANCE      = "ad_diag:performance"
_KEY_KEYWORDS         = "ad_diag:keywords"
_KEY_KW_PERFORMANCE   = "ad_diag:kw_performance"
_KEY_DAILY_PERF       = "ad_diag:daily_performance"
_KEY_CHANGE_HISTORY   = "ad_diag:change_history"
_KEY_PLACEMENT        = "ad_diag:placement"
_KEY_COVARIATES       = "ad_diag:covariates"

# ── L2 cache helpers (DataCache-backed, multi-tenant safe) ──────────────────
# Key format: {tenant_id}:{store_id}:{part...}
# - tenant_id isolates different seller accounts (multi-user safety)
# - store_id isolates marketplaces (US / EU / JP)
# - extra parts carry data-type-specific discriminators (days, asin, ids_hash)
#
# DataCache auto-selects Redis (if REDIS_URL set) or JSON-file backend.
# L1 (ctx.cache) is always checked first — L2 is only hit on job start / resume.

_L2_DOMAIN = "ad_diag"
_TTL_STATIC = 3600   # campaigns, keywords — account config, stable within a session
_TTL_PERF   = 3600   # performance reports — fetched once per day range
_TTL_CHANGE = 1800   # change history — more volatile, shorter TTL


def _l2_key(ctx: WorkflowContext, *parts) -> str:
    tid = ctx.tenant_id or "default"
    sid = ctx.config.get("store_id", "US")
    return ":".join(str(p) for p in (tid, sid) + parts)


def _l2_get(ctx: WorkflowContext, ttl: int, *parts):
    return _data_cache.get(_L2_DOMAIN, _l2_key(ctx, *parts), ttl_seconds=ttl)


def _l2_set(ctx: WorkflowContext, value, *parts) -> None:
    _data_cache.set(_L2_DOMAIN, _l2_key(ctx, *parts), value)


# Noise thresholds — changes smaller than these are low-signal
_NOISE_BID_PCT    = 0.05  # bid changes < 5% → low_weight
_NOISE_BUDGET_PCT = 0.10  # budget changes < 10% → low_weight

# Attribution priority: higher = analysed first in the LLM prompt
_CHANGE_PRIORITY: Dict[str, int] = {
    "SMART_BIDDING_STRATEGY": 6,
    "PLACEMENT_GROUP":        5,
    "BID_AMOUNT":             4,
    "BUDGET_AMOUNT":          3,
    "STATUS":                 2,
    "IN_BUDGET":              1,  # auto-generated by Amazon, not a manual action
}


def _store_tz(ctx: WorkflowContext) -> ZoneInfo:
    """
    Return the store's reporting timezone.

    Three data sources must share the same calendar date definition:
      - Amazon Ads change history  : UTC epoch-ms → must be converted here
      - Amazon Ads performance report dates : already in this timezone
      - Xiyouzhaoci localDate      : ISO with tz offset (e.g. -08:00/-07:00 Pacific)

    Config key "timezone" defaults to "America/Los_Angeles" (US stores).
    Other common values: "America/New_York", "Europe/London", "Asia/Tokyo".
    """
    return ZoneInfo(ctx.config.get("timezone", "America/Los_Angeles"))


# ---------------------------------------------------------------------------
# Shared account-level fetchers (fetch once, cached in ctx.cache)
# ---------------------------------------------------------------------------

async def _ensure_campaigns(ctx: WorkflowContext) -> List[Dict]:
    if _KEY_CAMPAIGNS not in ctx.cache:
        cached = _l2_get(ctx, _TTL_STATIC, "campaigns")
        if cached is not None:
            ctx.cache[_KEY_CAMPAIGNS] = cached
        else:
            from src.mcp.servers.amazon.ads.client import AmazonAdsClient
            store_id = ctx.config.get("store_id")
            region   = ctx.config.get("region", "NA")
            client   = AmazonAdsClient(store_id=store_id, region=region)
            campaigns = await client.list_campaigns(states=["ENABLED", "PAUSED"], max_results=2000)
            ctx.cache[_KEY_CAMPAIGNS] = campaigns
            _l2_set(ctx, campaigns, "campaigns")
            logger.info(f"Fetched {len(campaigns)} campaigns from Ads API")
    return ctx.cache[_KEY_CAMPAIGNS]


async def _ensure_performance(ctx: WorkflowContext) -> List[Dict]:
    if _KEY_PERFORMANCE not in ctx.cache:
        days   = ctx.config.get("days", 30)
        cached = _l2_get(ctx, _TTL_PERF, "sp_performance", days)
        if cached is not None:
            ctx.cache[_KEY_PERFORMANCE] = cached
        else:
            from src.mcp.servers.amazon.ads.client import AmazonAdsClient
            store_id = ctx.config.get("store_id")
            region   = ctx.config.get("region", "NA")
            client   = AmazonAdsClient(store_id=store_id, region=region)
            records  = await client.get_performance_report(
                report_type="spCampaigns", days=days
            )
            ctx.cache[_KEY_PERFORMANCE] = records
            _l2_set(ctx, records, "sp_performance", days)
            logger.info(f"Fetched {len(records)} campaign performance records")
    return ctx.cache[_KEY_PERFORMANCE]


async def _ensure_keyword_performance(ctx: WorkflowContext) -> List[Dict]:
    """Fetch account-wide spKeywords performance report, cached for the run."""
    if _KEY_KW_PERFORMANCE not in ctx.cache:
        days   = ctx.config.get("days", 30)
        cached = _l2_get(ctx, _TTL_PERF, "kw_performance", days)
        if cached is not None:
            ctx.cache[_KEY_KW_PERFORMANCE] = cached
        else:
            from src.mcp.servers.amazon.ads.client import AmazonAdsClient
            store_id = ctx.config.get("store_id")
            region   = ctx.config.get("region", "NA")
            client   = AmazonAdsClient(store_id=store_id, region=region)
            # spSearchTerm groups by search term but includes keywordText + matchType,
            # allowing us to aggregate up to keyword-level click/spend/order data.
            records  = await client.get_performance_report(
                report_type="spSearchTerm", days=days
            )
            ctx.cache[_KEY_KW_PERFORMANCE] = records
            _l2_set(ctx, records, "kw_performance", days)
            logger.info(f"Fetched {len(records)} keyword performance records")
    return ctx.cache[_KEY_KW_PERFORMANCE]


async def _ensure_keywords(ctx: WorkflowContext, campaign_ids: List[str]) -> List[Dict]:
    """Fetch keywords for a set of campaign_ids, cached by sorted id-tuple."""
    cache_key = f"{_KEY_KEYWORDS}:{','.join(sorted(campaign_ids))}"
    if cache_key not in ctx.cache:
        import hashlib as _hl
        ids_hash = _hl.md5(",".join(sorted(campaign_ids)).encode()).hexdigest()[:12]
        cached = _l2_get(ctx, _TTL_STATIC, "keywords", ids_hash)
        if cached is not None:
            ctx.cache[cache_key] = cached
        else:
            from src.mcp.servers.amazon.ads.client import AmazonAdsClient
            store_id = ctx.config.get("store_id")
            region   = ctx.config.get("region", "NA")
            client   = AmazonAdsClient(store_id=store_id, region=region)
            keywords = await client.list_keywords(
                campaign_ids=campaign_ids, states=["ENABLED", "PAUSED"]
            )
            ctx.cache[cache_key] = keywords
            _l2_set(ctx, keywords, "keywords", ids_hash)
    return ctx.cache[cache_key]


_ADVERT_PROD_MAX_DAYS = 31  # spAdvertisedProduct API window limit


async def _ensure_daily_performance(ctx: WorkflowContext, asin: str) -> List[Dict]:
    """
    Fetch spAdvertisedProduct daily report for the target ASIN.

    The full attribution window requires days + |ATTR_PRE_START| + |ATTR_POST_END| + 1
    days of data, which often exceeds the API's 31-day limit.  We issue multiple
    31-day chunks going backwards from yesterday and merge results, then filter
    client-side to the target ASIN (the API doesn't allow advertisedAsin filters
    with groupBy=advertiser).

    Cache key is per-ASIN so concurrent items don't collide.
    """
    cache_key = f"{_KEY_DAILY_PERF}:{asin}"
    if cache_key not in ctx.cache:
        days   = ctx.config.get("days", 30)
        cached = _l2_get(ctx, _TTL_PERF, "daily_perf", asin, days)
        if cached is not None:
            ctx.cache[cache_key] = cached
            return cached
        from src.mcp.servers.amazon.ads.client import AmazonAdsClient
        store_id    = ctx.config.get("store_id")
        region      = ctx.config.get("region", "NA")
        client      = AmazonAdsClient(store_id=store_id, region=region)
        days_needed = days + abs(ATTR_PRE_START) + abs(ATTR_POST_END) + 1

        today     = datetime.utcnow().date()
        chunk_end = today - timedelta(days=1)
        remaining = days_needed
        all_raw: List[Dict] = []

        while remaining > 0:
            chunk      = min(remaining, _ADVERT_PROD_MAX_DAYS)
            chunk_start = chunk_end - timedelta(days=chunk - 1)
            batch = await client.get_performance_report(
                report_type="spAdvertisedProduct",
                start_date=str(chunk_start),
                end_date=str(chunk_end),
                time_unit="DAILY",
            )
            all_raw.extend(batch)
            chunk_end  = chunk_start - timedelta(days=1)
            remaining -= chunk

        records = [r for r in all_raw if r.get("advertised_asin") == asin]
        ctx.cache[cache_key] = records
        _l2_set(ctx, records, "daily_perf", asin, days)
        chunks = -(-days_needed // _ADVERT_PROD_MAX_DAYS)  # ceiling div
        logger.info(
            f"[daily_perf] {asin}: {len(records)}/{len(all_raw)} records "
            f"({days_needed}d, {chunks} chunk(s))"
        )
    return ctx.cache[cache_key]


async def _ensure_placement_performance(ctx: WorkflowContext) -> List[Dict]:
    """Fetch account-wide spCampaignsPlacement report, cached once per run."""
    if _KEY_PLACEMENT not in ctx.cache:
        days   = ctx.config.get("days", 30)
        cached = _l2_get(ctx, _TTL_PERF, "placement", days)
        if cached is not None:
            ctx.cache[_KEY_PLACEMENT] = cached
        else:
            from src.mcp.servers.amazon.ads.client import AmazonAdsClient
            store_id = ctx.config.get("store_id")
            region   = ctx.config.get("region", "NA")
            client   = AmazonAdsClient(store_id=store_id, region=region)
            records  = await client.get_performance_report(
                report_type="spCampaignsPlacement", days=days
            )
            ctx.cache[_KEY_PLACEMENT] = records
            _l2_set(ctx, records, "placement", days)
            logger.info(f"Fetched {len(records)} placement performance records")
    return ctx.cache[_KEY_PLACEMENT]


async def _ensure_change_history(ctx: WorkflowContext) -> List[Dict]:
    """Fetch change history for the lookback window + attribution tail, cached once."""
    if _KEY_CHANGE_HISTORY not in ctx.cache:
        days   = ctx.config.get("days", 30)
        cached = _l2_get(ctx, _TTL_CHANGE, "change_history", days)
        if cached is not None:
            ctx.cache[_KEY_CHANGE_HISTORY] = cached
            return cached
        from src.mcp.servers.amazon.ads.client import AmazonAdsClient
        store_id = ctx.config.get("store_id")
        region   = ctx.config.get("region", "NA")
        client   = AmazonAdsClient(store_id=store_id, region=region)

        tz       = _store_tz(ctx)
        today    = datetime.now(tz=tz).date()
        # Extend window by ATTR_POST_END days so attribution tail is covered
        end_dt   = today - timedelta(days=1)
        start_dt = today - timedelta(days=days + abs(ATTR_POST_END))
        # Boundaries must be in store tz so the API returns events for the correct
        # local calendar days (e.g. an event at 23:30 PST would be next UTC day).
        to_ms   = int(datetime(end_dt.year,   end_dt.month,   end_dt.day,   23, 59, 59, tzinfo=tz).timestamp() * 1000)
        from_ms = int(datetime(start_dt.year, start_dt.month, start_dt.day,  0,  0,  0, tzinfo=tz).timestamp() * 1000)

        # No campaign_ids: API only supports useProfileIdAdvertiser:true (profile-wide).
        # Per-ASIN filtering happens client-side in _enrich_change_history.
        result = await client.get_change_history(
            from_date=from_ms,
            to_date=to_ms,
            count=200,
            sort_direction="DESC",
        )
        events = result.get("events", [])
        ctx.cache[_KEY_CHANGE_HISTORY] = events
        _l2_set(ctx, events, "change_history", days)
        logger.info(f"Fetched {len(events)} change history events")
    return ctx.cache[_KEY_CHANGE_HISTORY]


# ---------------------------------------------------------------------------
# Per-ASIN enrichers
# ---------------------------------------------------------------------------

async def _enrich_catalog(item: Dict, ctx: WorkflowContext) -> Dict:
    """Fetch product title, brand, size from SP-API Catalog."""
    from src.mcp.servers.amazon.sp_api.client import SPAPIClient
    asin = item.get("asin")
    if not asin:
        return {}
    try:
        client = SPAPIClient(store_id=ctx.config.get("store_id"))
        data   = await client.get_catalog_item(asin)
        return {
            "title":              data.get("title"),
            "brand":              data.get("brand"),
            "size":               data.get("size"),
            "bullet_point_count": data.get("bullet_point_count"),
        }
    except Exception as e:
        logger.warning(f"Catalog fetch failed for {asin}: {e}")
        return {}


async def _enrich_inventory(item: Dict, ctx: WorkflowContext) -> Dict:
    """Fetch FBA inventory for the item's SKU(s) from SP-API."""
    from src.mcp.servers.amazon.sp_api.client import SPAPIClient
    asin = item.get("asin")
    sku  = item.get("sku")
    try:
        client  = SPAPIClient(store_id=ctx.config.get("store_id"))
        records = await client.get_inventory(seller_skus=[sku] if sku else None)
        # Match by ASIN if no SKU filter was applied
        matched = [r for r in records if r.get("asin") == asin] if not sku else records
        if not matched:
            return {"inventory_records": [], "total_available": 0}
        total_available = sum(r.get("available_quantity", 0) for r in matched)
        total_inbound   = sum(r.get("inbound_quantity", 0)   for r in matched)
        # Estimate can-sell days using item daily sales if provided
        daily_sales = item.get("daily_sales") or 0
        can_sell_days = (
            round(total_available / daily_sales) if daily_sales > 0 else None
        )
        return {
            "inventory_records":  matched,
            "total_available":    total_available,
            "total_inbound":      total_inbound,
            "can_sell_days":      can_sell_days,
            "inventory_risk":     (
                can_sell_days is not None
                and can_sell_days < ctx.config.get("inventory_risk_days", 30)
            ),
        }
    except Exception as e:
        logger.warning(f"Inventory fetch failed for {asin}: {e}")
        return {"inventory_records": [], "total_available": 0, "inventory_risk": False}


async def _enrich_campaigns(item: Dict, ctx: WorkflowContext) -> Dict:
    """
    Match account campaigns to this ASIN by name convention (ASIN substring match).
    Returns empty campaign list if no match — falling back to all campaigns would
    contaminate the diagnosis with unrelated data.
    """
    asin = item.get("asin", "").upper()
    all_campaigns = await _ensure_campaigns(ctx)

    matched = [c for c in all_campaigns if asin in c.get("name", "").upper()]
    if not matched:
        logger.warning(f"No campaigns matched ASIN {asin} by name. Returning empty — "
                       f"add the ASIN to campaign names or pass campaign_ids explicitly.")
        return {"campaigns": [], "campaign_ids": [], "total_daily_budget": 0, "bidding_strategies": []}

    campaign_ids = [str(c["campaign_id"]) for c in matched]
    total_daily_budget = sum(
        c.get("daily_budget") or 0 for c in matched if c.get("state") == "ENABLED"
    )
    strategies = list({c.get("bidding_strategy") for c in matched if c.get("bidding_strategy")})

    return {
        "campaigns":          matched,
        "campaign_ids":       campaign_ids,
        "total_daily_budget": total_daily_budget,
        "bidding_strategies": strategies,
    }


async def _enrich_performance(item: Dict, ctx: WorkflowContext) -> Dict:
    """Filter performance report records to this ASIN's campaigns."""
    campaign_ids = set(item.get("campaign_ids", []))
    all_perf     = await _ensure_performance(ctx)

    matched = [
        r for r in all_perf
        if str(r.get("campaign_id")) in campaign_ids
    ] if campaign_ids else all_perf

    if not matched:
        return {"performance_records": [], "total_spend": 0, "account_acos": None}

    total_spend  = sum(r.get("spend",  0) or 0 for r in matched)
    total_sales  = sum(r.get("sales",  0) or 0 for r in matched)
    total_orders = sum(r.get("orders", 0) or 0 for r in matched)
    total_clicks = sum(r.get("clicks", 0) or 0 for r in matched)
    account_acos = round(total_spend / total_sales * 100, 2) if total_sales > 0 else None

    # Flag campaigns exceeding ACOS thresholds
    warn_thresh = ctx.config.get("acos_warn_threshold", 0.30) * 100
    crit_thresh = ctx.config.get("acos_crit_threshold", 0.50) * 100
    high_acos_campaigns = [
        r for r in matched
        if r.get("acos") and r["acos"] > warn_thresh
    ]

    # Budget exhaustion: spend / (daily_budget * days) > threshold
    days = ctx.config.get("days", 30)
    budget_pct_threshold = ctx.config.get("budget_exhaustion_pct", 0.90)
    total_budget_capacity = item.get("total_daily_budget", 0) * days
    budget_exhaustion_pct = (
        round(total_spend / total_budget_capacity, 4)
        if total_budget_capacity > 0 else None
    )

    # Backfill can_sell_days: fetch_inventory runs in Stage 1 before performance
    # data is available, so daily_sales is unknown at that point.  Derive it here
    # from ad orders / days (a conservative lower bound — excludes organic orders).
    result: Dict = {
        "performance_records":    matched,
        "total_spend":            total_spend,
        "total_sales":            total_sales,
        "total_orders":           total_orders,
        "total_clicks":           total_clicks,
        "account_acos":           account_acos,
        "high_acos_campaigns":    high_acos_campaigns,
        "budget_exhaustion_pct":  budget_exhaustion_pct,
        "budget_likely_exhausted": (
            budget_exhaustion_pct is not None
            and budget_exhaustion_pct > budget_pct_threshold
        ),
    }
    if item.get("can_sell_days") is None and total_orders > 0:
        daily_sales_ad = total_orders / days
        total_available = item.get("total_available") or 0
        if total_available > 0:
            can_sell_days = round(total_available / daily_sales_ad)
            result["daily_sales"]   = round(daily_sales_ad, 2)
            result["can_sell_days"] = can_sell_days
            result["inventory_risk"] = can_sell_days < ctx.config.get("inventory_risk_days", 30)
            logger.info(
                f"[backfill can_sell_days] {item.get('asin')}: "
                f"ad_orders={total_orders}/{days}d → daily_sales≈{daily_sales_ad:.1f}, "
                f"available={total_available}, can_sell_days={can_sell_days}"
            )
    return result


async def _enrich_keywords(item: Dict, ctx: WorkflowContext) -> Dict:
    """Fetch manual keywords for this ASIN's campaigns."""
    campaign_ids = item.get("campaign_ids", [])
    if not campaign_ids:
        return {"keywords": [], "keyword_count": 0}

    keywords = await _ensure_keywords(ctx, campaign_ids)

    # Summarise bid distribution
    bids = [k["bid"] for k in keywords if k.get("bid") is not None]
    avg_bid = round(sum(bids) / len(bids), 4) if bids else None
    match_type_dist = {}
    for k in keywords:
        mt = k.get("match_type", "UNKNOWN")
        match_type_dist[mt] = match_type_dist.get(mt, 0) + 1

    return {
        "keywords":         keywords,
        "keyword_count":    len(keywords),
        "avg_bid":          avg_bid,
        "min_bid":          min(bids, default=None),
        "max_bid":          max(bids, default=None),
        "match_type_dist":  match_type_dist,
    }


async def _enrich_keyword_performance(item: Dict, ctx: WorkflowContext) -> Dict:
    """
    Fetch keyword-level performance (spKeywords report) and aggregate per
    (keyword_text, match_type): avg_cpc, cvr, daily_clicks, impressions.

    Only keywords with >= min_clicks_for_cvr clicks are included to ensure
    reliable CVR estimates for the LP optimizer.
    """
    campaign_ids = set(item.get("campaign_ids", []))
    days         = ctx.config.get("days", 30)
    min_clicks   = ctx.config.get("min_clicks_for_cvr", 5)

    all_kw_perf = await _ensure_keyword_performance(ctx)

    # Filter to this ASIN's campaigns
    relevant = [
        r for r in all_kw_perf
        if str(r.get("campaign_id")) in campaign_ids
    ] if campaign_ids else all_kw_perf

    # Aggregate by (keyword_text, match_type)
    agg: Dict[tuple, Dict] = {}
    for r in relevant:
        key = (r.get("keyword_text", ""), r.get("match_type", ""))
        if key not in agg:
            agg[key] = {"spend": 0, "clicks": 0, "orders": 0, "impressions": 0, "sales": 0}
        agg[key]["spend"]       += r.get("spend", 0) or 0
        agg[key]["clicks"]      += r.get("clicks", 0) or 0
        agg[key]["orders"]      += r.get("orders", 0) or 0
        agg[key]["impressions"] += r.get("impressions", 0) or 0
        agg[key]["sales"]       += r.get("sales", 0) or 0

    kw_performance = []
    for (kw_text, match_type), v in agg.items():
        clicks = v["clicks"]
        if clicks < min_clicks:
            continue
        avg_cpc      = round(v["spend"] / clicks, 4)
        cvr          = round(v["orders"] / clicks, 4)
        daily_clicks = round(clicks / days, 2)
        # ACOS = ad spend / attributed sales revenue (not spend/orders which gives cost/order)
        acos = round(v["spend"] / v["sales"] * 100, 2) if v["sales"] > 0 else None
        kw_performance.append({
            "keyword_text":  kw_text,
            "match_type":    match_type,
            "total_spend":   round(v["spend"], 2),
            "total_sales":   round(v["sales"], 2),
            "total_clicks":  clicks,
            "total_orders":  v["orders"],
            "impressions":   v["impressions"],
            "avg_cpc":       avg_cpc,
            "cvr":           cvr,
            "daily_clicks":  daily_clicks,
            "acos":          acos,
        })

    # Sort by spend descending (most important keywords first)
    kw_performance.sort(key=lambda x: x["total_spend"], reverse=True)

    return {"keyword_performance": kw_performance}


async def _enrich_placement(item: Dict, ctx: WorkflowContext) -> Dict:
    """
    Aggregate spCampaignsPlacement report to per-placement spend/ACOS for this
    ASIN's campaigns.  Compares actual placement performance to configured bid
    adjustments so the LLM can recommend raising/lowering placement modifiers.
    """
    campaign_ids = set(item.get("campaign_ids", []))
    all_records  = await _ensure_placement_performance(ctx)

    # Filter to this ASIN's campaigns
    relevant = [
        r for r in all_records
        if str(r.get("campaign_id")) in campaign_ids
    ] if campaign_ids else all_records

    # Aggregate by placement label
    agg: Dict[str, Dict] = {}
    for r in relevant:
        p = r.get("placement") or "UNKNOWN"
        slot = agg.setdefault(p, {"spend": 0.0, "sales": 0.0, "clicks": 0, "impressions": 0, "orders": 0})
        slot["spend"]       += r.get("spend") or r.get("cost") or 0
        slot["sales"]       += r.get("sales") or 0
        slot["clicks"]      += r.get("clicks") or 0
        slot["impressions"] += r.get("impressions") or 0
        slot["orders"]      += r.get("orders") or 0

    placement_performance: Dict[str, Dict] = {}
    total_spend = sum(v["spend"] for v in agg.values()) or 1  # avoid /0
    for p, m in agg.items():
        spend = m["spend"]
        sales = m["sales"]
        placement_performance[p] = {
            "spend":         round(spend, 2),
            "sales":         round(sales, 2),
            "clicks":        m["clicks"],
            "impressions":   m["impressions"],
            "orders":        m["orders"],
            "acos":          round(spend / sales * 100, 2) if sales > 0 else None,
            "spend_share":   round(spend / total_spend * 100, 2),
            "ctr":           round(m["clicks"] / m["impressions"] * 100, 4) if m["impressions"] > 0 else None,
        }

    # Attach configured bid adjustments from campaign data for easy comparison
    campaigns = item.get("campaigns", [])
    configured_adjustments: Dict[str, Optional[float]] = {}
    for c in campaigns:
        for key, label in [
            ("placement_top_of_search_pct", "PLACEMENT_TOP_OF_SEARCH"),
            ("placement_product_page_pct",  "PLACEMENT_PRODUCT_PAGE"),
        ]:
            pct = c.get(key)
            if pct is not None:
                existing = configured_adjustments.get(label)
                configured_adjustments[label] = max(existing or 0, pct)

    return {
        "placement_performance":      placement_performance,
        "placement_configured_pcts":  configured_adjustments,
    }


async def _enrich_change_history(item: Dict, ctx: WorkflowContext) -> Dict:
    """
    Filter change history to this ASIN's campaigns, apply noise filter,
    detect compound changes (multiple dimensions within 48h on same campaign).

    _ensure_daily_performance is gathered concurrently here intentionally:
    _correlate_changes is a synchronous ProcessStep that reads daily_perf from
    ctx.cache. It runs AFTER all EnrichStep items complete, so the cache must
    be populated before then. Fetching it here (in parallel with change_history)
    ensures it is warmed — do NOT remove this gather without moving the fetch elsewhere.
    """
    asin         = item.get("asin", "").upper()
    campaign_ids = set(item.get("campaign_ids") or [])
    all_events, _ = await asyncio.gather(
        _ensure_change_history(ctx),
        _ensure_daily_performance(ctx, asin),
    )

    relevant = []
    for ev in all_events:
        # Campaign ID: prefer metadata.campaignId (AD_GROUP/KEYWORD events),
        # fall back to entityId for CAMPAIGN-level events.
        meta = ev.get("metadata") or {}
        cid  = str(meta.get("campaignId") or ev.get("entityId") or "")

        # Filter to this ASIN's campaigns since we now fetch profile-wide
        if campaign_ids and cid not in campaign_ids:
            continue

        # Noise filter: IN_BUDGET is auto-generated (not a human action); tiny tweaks are low-signal
        change_type = ev.get("changeType", "")
        old_val = ev.get("previousValue")
        new_val = ev.get("newValue")
        is_low_weight = change_type == "IN_BUDGET"  # always low_weight — Amazon auto-event
        if not is_low_weight and change_type in ("BID_AMOUNT", "BUDGET_AMOUNT") and old_val and new_val:
            try:
                old_f, new_f = float(old_val), float(new_val)
                if old_f > 0:
                    threshold = _NOISE_BID_PCT if change_type == "BID_AMOUNT" else _NOISE_BUDGET_PCT
                    if abs(new_f - old_f) / old_f < threshold:
                        is_low_weight = True
            except (TypeError, ValueError):
                pass

        relevant.append({
            "event_id":     ev.get("eventId"),
            "campaign_id":  cid,
            "entity_type":  ev.get("entityType"),
            "entity_id":    ev.get("entityId"),
            "change_type":  change_type,
            "old_value":    old_val,
            "new_value":    new_val,
            "changed_at":   ev.get("changedAt") or ev.get("timestamp"),
            "priority":     _CHANGE_PRIORITY.get(change_type, 0),
            "low_weight":   is_low_weight,
            "keyword":      meta.get("keyword"),
            "keyword_type": meta.get("keywordType"),
            "ad_group_id":  meta.get("adGroupId"),
        })

    # Compound change detection: same campaign, >1 dimension within 48h
    compound_flag: Dict[str, bool] = {}
    for ev in relevant:
        cid = ev["campaign_id"]
        ts  = ev.get("changed_at")
        if not ts:
            continue
        try:
            t0 = int(ts) / 1000  # epoch ms → seconds
        except (TypeError, ValueError):
            continue
        siblings = [
            e for e in relevant
            if e["campaign_id"] == cid
            and e["change_type"] != ev["change_type"]
            and e.get("changed_at")
            and abs(int(e["changed_at"]) / 1000 - t0) <= 48 * 3600
        ]
        if siblings:
            compound_flag[cid] = True

    for ev in relevant:
        ev["compound_change"] = compound_flag.get(ev["campaign_id"], False)

    # Surface only meaningful (non-low-weight) changes, up to 50
    notable = [e for e in relevant if not e["low_weight"]]
    return {
        "change_events":       notable[:50],
        "change_event_count":  len(notable),
        "has_compound_change": any(e["compound_change"] for e in notable),
    }


def _optimize_budget(items: List[Dict], ctx: WorkflowContext) -> List[Dict]:
    """
    ProcessStep (pure Python): run LP budget optimisation for each item.

    Inputs per item (set by previous steps):
      keyword_performance  list of per-keyword aggregated metrics
      total_daily_budget   float — campaign budget cap

    LP formulation (via AdBudgetOptimizer / OR-Tools GLOP):
      Maximise  Σ clicks_i × cvr_i          (= expected orders)
      Subject to Σ clicks_i × avg_cpc_i ≤ daily_budget
                 0 ≤ clicks_i ≤ max_daily_clicks_i

    max_daily_clicks_i = daily_clicks × headroom_factor (default 3×)
    — allows the solver to explore expanding high-CVR keywords.

    Adds to each item:
      lp_summary          overall budget efficiency metrics
      lp_top_allocations  top keywords by LP-assigned clicks (increase budget here)
      lp_zero_keywords    keywords LP dropped to 0 (pause candidates)
      lp_maxed_keywords   keywords hitting the ceiling (raise bid / budget)
      lp_actual_orders    estimated orders at current spend (for comparison)
    """
    from src.intelligence.processors.optimizer_ad_budget import AdBudgetOptimizer

    headroom = ctx.config.get("lp_headroom_factor", 3.0)
    optimizer = AdBudgetOptimizer()

    for item in items:
        kw_perf        = item.get("keyword_performance", [])
        daily_budget   = item.get("total_daily_budget", 0) or 0

        if not kw_perf or daily_budget <= 0:
            item["lp_summary"] = {"skipped": True, "reason": "no keyword data or zero budget"}
            continue

        # Build LP input — one row per (keyword, match_type) with enough data
        lp_input = []
        actual_daily_orders = 0.0
        for kw in kw_perf:
            if not kw.get("avg_cpc") or not kw.get("cvr"):
                continue
            max_daily = max(round(kw["daily_clicks"] * headroom, 1), 1.0)
            lp_input.append({
                "name":              f"{kw['keyword_text']}|{kw['match_type']}",
                "avg_cpc":           kw["avg_cpc"],
                "estimated_cvr":     kw["cvr"],
                "max_daily_clicks":  max_daily,
            })
            actual_daily_orders += kw["daily_clicks"] * kw["cvr"]

        if not lp_input:
            item["lp_summary"] = {"skipped": True, "reason": "all keywords filtered (insufficient clicks)"}
            continue

        result = optimizer.optimize(lp_input, total_budget=daily_budget)

        if result.get("status") != "OPTIMAL":
            item["lp_summary"] = {"skipped": True, "reason": result.get("message")}
            continue

        summary  = result["summary"]
        alloc    = result["allocation"]
        alloc_names = {a["keyword"] for a in alloc}

        # Keywords LP assigned 0 clicks → pause candidates
        zero_kws = [
            kw["keyword_text"] for kw in kw_perf
            if f"{kw['keyword_text']}|{kw['match_type']}" not in alloc_names
            and kw.get("avg_cpc")
        ]

        # Keywords at LP ceiling → raise bid / increase budget candidates
        maxed_kws = []
        kw_map = {lp["name"]: lp for lp in lp_input}
        for a in alloc:
            cap = kw_map.get(a["keyword"], {}).get("max_daily_clicks", 0)
            if cap and a["optimized_clicks"] >= cap * 0.95:
                maxed_kws.append(a["keyword"].split("|")[0])

        optimal_orders = summary["total_expected_orders"]
        item["lp_summary"] = {
            "daily_budget":           daily_budget,
            "lp_optimal_spend":       summary["actual_spend"],
            "lp_optimal_orders":      optimal_orders,
            "actual_daily_orders":    round(actual_daily_orders, 2),
            "order_gap":              round(optimal_orders - actual_daily_orders, 2),
            "avg_effective_cpc":      summary["avg_effective_cpc"],
            "keywords_in_lp":         len(lp_input),
            "keywords_allocated":     len(alloc),
            "keywords_zeroed":        len(zero_kws),
            "keywords_maxed":         len(maxed_kws),
        }
        item["lp_top_allocations"] = alloc[:10]    # top 10 by clicks
        item["lp_zero_keywords"]   = zero_kws[:20] # pause candidates
        item["lp_maxed_keywords"]  = maxed_kws[:10]# raise-bid candidates

    return items


async def _enrich_covariates(item: Dict, ctx: WorkflowContext) -> Dict:
    """
    Fetch daily price / promotion / rating time series via Xiyouzhaoci get_asin_daily_trends.

    Covers the same window as the change-history lookback so that run_causal_analysis
    can annotate each change event with the covariate state on the change date.

    Returned covariate_series shape:
        {"2026-04-01": {"list_price": 29.99, "sale_price": 24.99,
                        "promotion_flag": true, "rating": 4.6, "review_count": 312}, ...}

    Note: get_asin_daily_trends is historical time-series data (Xiyouzhaoci).
          ProductDetailsExtractor gives only a point-in-time page scrape — not suitable
          for ITS/CausalImpact/DML which require day-indexed covariate vectors.
    """
    if not ctx.config.get("enable_xiyou", True):
        return {}

    asin    = item.get("asin")
    country = ctx.config.get("country", "US")
    days    = ctx.config.get("days", 30)
    if not asin:
        return {}

    try:
        from src.mcp.servers.market.xiyouzhaoci.client import XiyouZhaociAPI
        api = XiyouZhaociAPI(tenant_id=ctx.config.get("tenant_id", "default"))

        tz     = ZoneInfo(ctx.config.get("timezone", "America/Los_Angeles"))
        today  = datetime.now(tz=tz).date()
        end_dt = today - timedelta(days=1)

        # Two-tier window:
        #   Attribution window  (days):                 aligns with change_history for Before/After
        #   Causal baseline window (rank_lookback_months): aligns with natural_rank_series for ITS
        # Use the longer of the two so covariate_series covers the full ITS baseline.
        import calendar as _cal
        rank_months = min(ctx.config.get("rank_lookback_months", 6), 24)
        rm_y = end_dt.year - (rank_months // 12)
        rm_m = end_dt.month - (rank_months % 12)
        if rm_m <= 0:
            rm_m += 12; rm_y -= 1
        from datetime import date as _date
        causal_start = _date(rm_y, rm_m, min(end_dt.day, _cal.monthrange(rm_y, rm_m)[1]))
        attr_start   = today - timedelta(days=days + abs(ATTR_POST_END))
        start_dt     = min(causal_start, attr_start)

        raw = api.get_asin_daily_trends(
            country=country,
            asin=asin,
            start_date=start_dt.strftime("%Y-%m-%d"),
            end_date=end_dt.strftime("%Y-%m-%d"),
        )
        if not raw:
            return {}

        # Response shape: {"entities": [{"country": ..., "asin": ..., "trends": [...]}]}
        # Each trend record: {"localDate": "2026-01-01T00:00:00-08:00", "price": 43.99,
        #   "ratings": 5325, "stars": 4,
        #   "priceDistribution": {"deal": false, "originPrice": 54.99, "prime": 43.99}}
        entities = raw.get("entities") or []
        entity   = next((e for e in entities if e.get("asin") == asin), entities[0] if entities else {})
        records  = entity.get("trends") or []

        tz               = ZoneInfo(ctx.config.get("timezone", "America/Los_Angeles"))
        covariate_series: Dict[str, Dict] = {}
        for r in records:
            # localDate carries a UTC offset (e.g. "2026-01-01T00:00:00-08:00").
            # Parse the full ISO string so DST transitions are handled correctly,
            # then express the date in the store timezone — matching the date key
            # used by performance-report records and change-history anchors.
            raw_date = r.get("localDate") or ""
            try:
                dt_with_offset = datetime.fromisoformat(str(raw_date))
                date = dt_with_offset.astimezone(tz).strftime("%Y-%m-%d")
            except (ValueError, TypeError):
                date = str(raw_date)[:10]
            if len(date) != 10:
                continue

            price_dist  = r.get("priceDistribution") or {}
            list_price  = price_dist.get("originPrice")          # original/list price
            sale_price  = r.get("price")                         # effective price (prime)
            is_deal     = bool(price_dist.get("deal", False))
            rating      = r.get("stars")
            review_cnt  = r.get("ratings")

            # Promotion flag: explicit deal OR effective price < 95% of list price
            try:
                price_promo = bool(
                    list_price and sale_price and
                    float(sale_price) < float(list_price) * 0.95
                )
            except (TypeError, ValueError):
                price_promo = False
            promo = is_deal or price_promo

            covariate_series[date] = {
                "list_price":     float(list_price)  if list_price  is not None else None,
                "sale_price":     float(sale_price)  if sale_price  is not None else None,
                "is_deal":        is_deal,
                "promotion_flag": promo,
                "rating":         float(rating)      if rating      is not None else None,
                "review_count":   int(review_cnt)    if review_cnt  is not None else None,
            }

        if not covariate_series:
            logger.warning(f"No covariate records parsed for {asin}")
            return {}

        prices  = [v["sale_price"]  for v in covariate_series.values() if v["sale_price"]  is not None]
        ratings = [v["rating"]      for v in covariate_series.values() if v["rating"]      is not None]
        promo_days = sum(1 for v in covariate_series.values() if v["promotion_flag"])

        logger.info(f"Covariates for {asin}: {len(covariate_series)} days, "
                    f"{promo_days} promo days, price {min(prices, default=0):.2f}–{max(prices, default=0):.2f}")
        return {
            "covariate_series": covariate_series,
            "price_min":        round(min(prices), 2)                         if prices  else None,
            "price_max":        round(max(prices), 2)                         if prices  else None,
            "price_mean":       round(sum(prices) / len(prices), 2)           if prices  else None,
            "promotion_days":   promo_days,
            "rating_latest":    ratings[-1]                                   if ratings else None,
            "rating_delta":     round(ratings[-1] - ratings[0], 2)            if len(ratings) >= 2 else None,
        }

    except Exception as e:
        logger.warning(f"Covariate fetch failed for {asin}: {e}")
        return {}


async def _enrich_competitor_prices(item: Dict, ctx: WorkflowContext) -> Dict:
    """
    Identify competitor ASINs via keyword-level topAsins data, then fetch their
    daily price history as an external covariate for ITS/CausalImpact/DML.

    Pipeline:
      1. get_asin_keywords  → top keywords for this ASIN (synchronous list endpoint)
      2. Filter brand keywords: term contains brand name OR target ASIN click share > 50%
      3. Top 5 non-brand keywords by weeklySearchVolume
      4. topAsins[:3] per keyword → deduplicate → ≤15 competitor ASINs
      5. get_asin_daily_trends for each competitor (parallel via asyncio.to_thread)
      6. Build per-date summary {min, max, median} across all competitors

    Depends on: fetch_catalog (provides brand name for keyword filtering).
    Must run after Stage 1 catalog enrichment.
    """
    if not ctx.config.get("enable_xiyou", True):
        return {}

    asin    = item.get("asin")
    brand   = (item.get("brand") or "").lower().strip()
    country = ctx.config.get("country", "US")
    days    = ctx.config.get("days", 30)
    tz      = _store_tz(ctx)
    if not asin:
        return {}

    try:
        from src.mcp.servers.market.xiyouzhaoci.client import XiyouZhaociAPI
        api = XiyouZhaociAPI(tenant_id=ctx.config.get("tenant_id", "default"))

        today    = datetime.now(tz=tz).date()
        kw_end   = today - timedelta(days=1)
        kw_start = today - timedelta(days=30)   # keyword data: last 30 days

        kw_data = await asyncio.to_thread(
            api.get_asin_keywords,
            country, asin,
            kw_start.strftime("%Y-%m-%d"),
            kw_end.strftime("%Y-%m-%d"),
            1, 20,
        )
        kw_list = kw_data.get("list") or []

        # ── Filter brand keywords, rank by search volume ──────────────────
        non_brand: List[tuple] = []
        for kw in kw_list:
            term = (kw.get("searchTerm") or "").lower()
            # Brand keyword: search term contains the brand name
            if brand and brand in term:
                continue
            # Brand keyword: target ASIN dominates click share (>50%)
            top_asins = (kw.get("topAsins") or {}).get("list") or []
            own_share = next(
                (a.get("clickShare", 0) for a in top_asins if a.get("asin") == asin), 0
            )
            if own_share > 0.5:
                continue
            vol = (kw.get("searchTermReport") or {}).get("weeklySearchVolume", 0) or 0
            non_brand.append((vol, kw))

        non_brand.sort(key=lambda x: x[0], reverse=True)
        top_kws = [kw for _, kw in non_brand[:5]]

        # ── Collect top 3 competitor ASINs per keyword, deduplicate ──────
        competitor_asins: List[str] = []
        seen = {asin}
        for kw in top_kws:
            for entry in ((kw.get("topAsins") or {}).get("list") or [])[:3]:
                comp = entry.get("asin")
                if comp and comp not in seen:
                    competitor_asins.append(comp)
                    seen.add(comp)

        if not competitor_asins:
            logger.warning(f"No competitor ASINs found for {asin}")
            return {"competitor_asins": [], "competitor_price_summary": {}}

        # ── Fetch daily price history for each competitor (parallel) ─────
        cov_end   = today - timedelta(days=1)
        cov_start = today - timedelta(days=days + abs(ATTR_POST_END))

        async def _fetch_prices(comp_asin: str):
            try:
                raw = await asyncio.to_thread(
                    api.get_asin_daily_trends,
                    country, comp_asin,
                    cov_start.strftime("%Y-%m-%d"),
                    cov_end.strftime("%Y-%m-%d"),
                )
                entities = raw.get("entities") or []
                entity   = next(
                    (e for e in entities if e.get("asin") == comp_asin),
                    entities[0] if entities else {},
                )
                prices: Dict[str, float] = {}
                for r in entity.get("trends") or []:
                    try:
                        dt_local = datetime.fromisoformat(str(r.get("localDate") or ""))
                        date  = dt_local.astimezone(tz).strftime("%Y-%m-%d")
                        price = r.get("price")
                        if price is not None:
                            prices[date] = float(price)
                    except (ValueError, TypeError):
                        continue
                return comp_asin, prices
            except Exception as e:
                logger.warning(f"Competitor price fetch failed for {comp_asin}: {e}")
                return comp_asin, {}

        results = await asyncio.gather(*[_fetch_prices(a) for a in competitor_asins])
        comp_price_by_asin: Dict[str, Dict[str, float]] = dict(results)

        # ── Build per-date summary (min/max/median across competitors) ───
        all_dates = sorted({d for prices in comp_price_by_asin.values() for d in prices})
        competitor_price_summary: Dict[str, Dict] = {}
        for date in all_dates:
            day_prices = sorted(
                v for a in comp_price_by_asin for v in [comp_price_by_asin[a].get(date)] if v
            )
            if not day_prices:
                continue
            n      = len(day_prices)
            median = day_prices[n // 2] if n % 2 else (day_prices[n//2-1] + day_prices[n//2]) / 2
            competitor_price_summary[date] = {
                "min":    round(min(day_prices), 2),
                "max":    round(max(day_prices), 2),
                "median": round(median, 2),
                "count":  n,
            }

        logger.info(
            f"Competitor prices for {asin}: {len(competitor_asins)} ASINs, "
            f"{len(competitor_price_summary)} date points"
        )
        return {
            "competitor_asins":         competitor_asins,
            "competitor_price_by_asin": comp_price_by_asin,
            "competitor_price_summary": competitor_price_summary,
        }

    except Exception as e:
        logger.warning(f"Competitor price enrichment failed for {asin}: {e}")
        return {"competitor_asins": [], "competitor_price_summary": {}}


async def _enrich_xiyou_rankings(item: Dict, ctx: WorkflowContext) -> Dict:
    """
    Fetch organic keyword traffic scores and ABA ranking from Xiyouzhaoci.
    Returns ad_traffic_ratio and top organic search terms.
    """
    if not ctx.config.get("enable_xiyou", True):
        return {}

    asin    = item.get("asin")
    country = ctx.config.get("country", "US")
    if not asin:
        return {}

    try:
        from src.mcp.servers.market.xiyouzhaoci.client import XiyouZhaociAPI
        api   = XiyouZhaociAPI(tenant_id=ctx.config.get("tenant_id", "default"))
        scores = api.get_traffic_scores(country=country, asins=[asin])

        entities = scores.get("entities") or []
        if not entities:
            return {}

        entry = next((e for e in entities if e.get("asin") == asin), entities[0])
        return {
            "ad_traffic_ratio":      entry.get("advertisingTrafficScoreRatio"),
            "organic_traffic_ratio": entry.get("organicTrafficScoreRatio"),
            "traffic_growth_7d":     entry.get("totalTrafficScoreGrowthRate"),
            "xiyou_scores_raw":      entry,
        }
    except Exception as e:
        logger.warning(f"Xiyou traffic scores failed for {asin}: {e}")
        return {}


def _select_rank_keywords(item: Dict, top_n: int = 3) -> List[str]:
    """
    Choose the most signal-rich keywords for organic rank and market trend tracking.

    Priority order:
      1. lp_top_allocations — LP-validated efficient terms (high spend + positive CVR).
      2. keyword_performance sorted by total_spend, filtered ACOS ≤ 80%
         (avoid zero-CVR keywords that burn budget with no organic signal).

    Returns at most `top_n` unique lowercase keyword strings.
    """
    seen: list = []

    for entry in item.get("lp_top_allocations") or []:
        # lp_top_allocations stores "keyword text|MATCH_TYPE" — strip the suffix
        kw = (entry.get("keyword") or "").split("|")[0].strip().lower()
        if kw and kw not in seen:
            seen.append(kw)
        if len(seen) >= top_n:
            return seen

    kw_perf = sorted(
        item.get("keyword_performance") or [],
        key=lambda x: x.get("total_spend", 0),
        reverse=True,
    )
    for entry in kw_perf:
        acos = entry.get("acos")
        if acos is not None and acos > 80:
            continue
        kw = (entry.get("keyword_text") or "").strip().lower()
        if kw and kw not in seen:
            seen.append(kw)
        if len(seen) >= top_n:
            return seen

    return seen


async def _enrich_keyword_signals(item: Dict, ctx: WorkflowContext) -> Dict:
    """
    Fetch daily organic rank and weekly ABA market trends for the top-N keywords
    in a single enricher, avoiding duplicate keyword selection and API client setup.

    Keyword selection: _select_rank_keywords() called once — LP allocations first,
    fallback to top-spend keywords with ACOS ≤ 80%.

    Both API calls (rank trends, SFR trends) are issued concurrently via asyncio.gather.

    Returned keys:
        natural_rank_series   {keyword: {date: {page, pageRank, totalRank}}}
        rank_tracked_keywords list of keywords that returned rank data
        market_trends         {keyword: {YYYY-Www: {sfr, weekly_searches}}}
        market_trends_meta    {keyword: {current_sfr, current_weekly_searches}}
    """
    if not ctx.config.get("enable_xiyou", True):
        return {}

    asin    = item.get("asin")
    country = ctx.config.get("country", "US")
    if not asin:
        return {}

    keywords = _select_rank_keywords(item)
    if not keywords:
        logger.info(f"[keyword_signals] No keywords for {asin}, skipping.")
        return {}

    import calendar as _cal
    from datetime import date as _date

    rank_months  = min(ctx.config.get("rank_lookback_months", 6), 24)
    weeks_needed = rank_months * 4 + 4   # slight overestimate; API caps internally

    tz     = ZoneInfo(ctx.config.get("timezone", "America/Los_Angeles"))
    today  = datetime.now(tz=tz).date()
    end_dt = today - timedelta(days=1)

    # Calendar-month start date for rank series
    y, m = end_dt.year - (rank_months // 12), end_dt.month - (rank_months % 12)
    if m <= 0:
        m += 12; y -= 1
    rank_start = _date(y, m, min(end_dt.day, _cal.monthrange(y, m)[1]))

    try:
        from src.mcp.servers.market.xiyouzhaoci.client import XiyouZhaociAPI
        api = XiyouZhaociAPI(tenant_id=ctx.config.get("tenant_id", "default"))

        # ── Fetch rank trends and SFR trends concurrently ─────────────────────
        async def _fetch_rank() -> Dict:
            raw      = await asyncio.to_thread(
                api.get_asin_search_term_rank_trends,
                country, asin, keywords,
                rank_start.strftime("%Y-%m-%d"),
                end_dt.strftime("%Y-%m-%d"),
            )
            entities = raw.get("entities") or []
            series: Dict[str, Dict] = {}
            for entity in entities:
                term  = (entity.get("searchTerm") or "").strip().lower()
                daily: Dict[str, Dict] = {}
                for trend in entity.get("trends") or []:
                    try:
                        dt = datetime.fromisoformat(str(trend.get("localDate") or "")).astimezone(tz)
                        date_key = dt.strftime("%Y-%m-%d")
                    except Exception:
                        continue
                    or_pos = (trend.get("displayPositions") or {}).get("or") or {}
                    if or_pos:
                        daily[date_key] = {
                            "page":      or_pos.get("page"),
                            "pageRank":  or_pos.get("pageRank"),
                            "totalRank": or_pos.get("totalRank"),
                        }
                if daily:
                    series[term] = daily
            return series

        async def _fetch_trends() -> tuple:
            latest_monday = today - timedelta(days=today.weekday() + 7)
            trends: Dict[str, Dict] = {}
            meta:   Dict[str, Dict] = {}
            for kw in keywords:
                raw     = await asyncio.to_thread(api.get_search_term_trends, country, kw, weeks_needed)
                entries = raw.get("searchTerms") or []
                if not entries:
                    continue
                entry      = entries[0]
                sfr_arr    = (entry.get("trends") or {}).get("searchFrequencyRank") or []
                search_arr = (entry.get("trends") or {}).get("weekSearch") or []
                n = len(sfr_arr)
                if not n:
                    continue
                weekly: Dict[str, Dict] = {}
                for i, sfr in enumerate(sfr_arr):
                    week_monday = latest_monday - timedelta(days=(n - 1 - i) * 7)
                    weekly[week_monday.strftime("%G-W%V")] = {
                        "sfr":             sfr,
                        "weekly_searches": search_arr[i] if i < len(search_arr) else None,
                    }
                trends[kw] = weekly
                current    = entry.get("values") or {}
                meta[kw]   = {
                    "current_sfr":             current.get("searchFrequencyRank"),
                    "current_weekly_searches": current.get("weekSearch"),
                }
            return trends, meta

        rank_series, (market_trends, market_trends_meta) = await asyncio.gather(
            _fetch_rank(),
            _fetch_trends(),
        )

        logger.info(
            f"[keyword_signals] {asin}: rank={list(rank_series.keys())}, "
            f"trends={list(market_trends.keys())}"
        )
        return {
            "natural_rank_series":   rank_series,
            "rank_tracked_keywords": list(rank_series.keys()),
            "market_trends":         market_trends,
            "market_trends_meta":    market_trends_meta,
        }

    except Exception as e:
        logger.warning(f"[keyword_signals] Failed for {asin}: {e}")
        return {}


# ---------------------------------------------------------------------------
# Causal analysis wrapper (delegates to intelligence/processors/causal_analysis)
# ---------------------------------------------------------------------------

def _run_causal_analysis(items: List[Dict], ctx: WorkflowContext) -> List[Dict]:
    """
    ProcessStep wrapper: runs the full attribution + causal pipeline
    (window comparison, ITS, CausalImpact, DML) for each item.

    Passes daily_perf from cache so the processor can build the campaign-level
    daily performance index without depending on workflow internals.
    """
    from src.intelligence.processors.causal_analysis import run_causal_analysis
    for item in items:
        try:
            asin       = item.get("asin", "").upper()
            daily_perf = ctx.cache.get(f"{_KEY_DAILY_PERF}:{asin}", [])
            result = run_causal_analysis(item, ctx.config, daily_perf=daily_perf)
            item.update(result)
        except Exception as e:
            logger.warning(f"[causal_analysis] Failed for {item.get('asin', '?')}: {e}")
    return items


# ---------------------------------------------------------------------------
# LLM pre-enrichment (summary injection only — no field stripping)
# ---------------------------------------------------------------------------

def _build_item_summary(item: Dict) -> Dict:
    """
    Pre-compute a flat highlights dict from a fully enriched item.
    Python-side extraction: 100% accurate, zero LLM token cost.
    Mirrors the highlights dict in the live test's _print_result.
    """
    rank_series: Dict = item.get("natural_rank_series") or {}
    market_trends: Dict = item.get("market_trends") or {}
    attributions: List = item.get("change_attributions") or []
    return {
        "asin":                      item.get("asin"),
        "title":                     item.get("title"),
        "brand":                     item.get("brand"),
        "total_available":           item.get("total_available"),
        "can_sell_days":             item.get("can_sell_days"),
        "inventory_risk":            item.get("inventory_risk"),
        "campaign_count":            len(item.get("campaigns", [])),
        "total_daily_budget":        item.get("total_daily_budget"),
        "bidding_strategies":        item.get("bidding_strategies"),
        "total_spend":               item.get("total_spend"),
        "total_sales":               item.get("total_sales"),
        "total_orders":              item.get("total_orders"),
        "account_acos":              item.get("account_acos"),
        "budget_exhaustion_pct":     item.get("budget_exhaustion_pct"),
        "budget_likely_exhausted":   item.get("budget_likely_exhausted"),
        "keyword_count":             item.get("keyword_count"),
        "avg_bid":                   item.get("avg_bid"),
        "match_type_dist":           item.get("match_type_dist"),
        "kw_performance_count":      len(item.get("keyword_performance", [])),
        "lp_summary":                item.get("lp_summary"),
        "lp_top_allocations":        (item.get("lp_top_allocations") or [])[:3],
        "lp_zero_keywords":          (item.get("lp_zero_keywords") or [])[:5],
        "lp_maxed_keywords":         (item.get("lp_maxed_keywords") or [])[:5],
        "ad_traffic_ratio":          item.get("ad_traffic_ratio"),
        "organic_traffic_ratio":     item.get("organic_traffic_ratio"),
        "rank_tracked_keywords":     item.get("rank_tracked_keywords"),
        "rank_series_days":          len(next(iter(rank_series.values()), {})),
        "market_trends_keywords":    list(market_trends.keys()),
        "change_attributions_count": len(attributions),
        "causal_consensus_sample":   attributions[0].get("consensus") if attributions else None,
    }


def _prepare_for_llm(items: List[Dict], ctx: WorkflowContext) -> List[Dict]:
    """
    PURE_PYTHON step immediately before ad_diagnosis_llm.

    Injects _summary_json (Python-exact highlights) as a scalar field so
    ProcessStep auto-substitutes it into {_summary_json} in the prompt.
    Full item data is preserved — no fields are stripped.
    """
    import json as _json
    for item in items:
        item["_summary_json"] = _json.dumps(
            _build_item_summary(item), ensure_ascii=False, default=str
        )
    return items


def _export_report(items: List[Dict], ctx: WorkflowContext) -> List[Dict]:
    """
    PURE_PYTHON step after ad_diagnosis_llm.

    Writes the LLM report to data/reports/ad_diagnosis_{ASIN}_{date}.md and
    sets item["report_file_path"] so FeishuCallback.on_complete sends it as a
    file attachment automatically.

    Also sets item["response"] to a short preview so the card branch in
    on_complete shows a summary card instead of trying to upload the full
    text as a second attachment.
    """
    import os
    import datetime as _dt

    report_dir = os.path.abspath("data/reports")
    os.makedirs(report_dir, exist_ok=True)
    date_str = _dt.date.today().isoformat()

    for item in items:
        text = item.get("ad_diagnosis_llm") or ""
        if not text:
            continue
        asin = (item.get("asin") or "unknown").upper()
        filename = f"ad_diagnosis_{asin}_{date_str}.md"
        file_path = os.path.join(report_dir, filename)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(text)
        item["report_file_path"] = file_path
        # Short preview for the card — keeps on_complete from writing a second
        # temp file when it sees len(text) > 8000 in the card branch.
        item["response"] = (
            text[:400].rstrip()
            + f"\n\n…（完整报告已保存为 `{filename}`，正在发送为附件）"
        )
        logger.info(f"[export_report] {asin}: {len(text)} chars → {file_path}")
    return items


# ---------------------------------------------------------------------------
# Workflow builder
# ---------------------------------------------------------------------------

@WorkflowRegistry.register("ad_diagnosis")
def build_ad_diagnosis(config: dict) -> Workflow:
    """
    Build the ad diagnosis workflow.

    Each input item must contain at least {"asin": "B0XXXXXXXX"}.
    Optional per-item fields: sku, cogs, price, daily_sales.
    """
    steps = [
        # ── Stage 1: product & inventory context (parallel, independent) ──
        EnrichStep(
            name="fetch_catalog",
            extractor_fn=_enrich_catalog,
            parallel=True,
            concurrency=5,
        ),
        EnrichStep(
            name="fetch_inventory",
            extractor_fn=_enrich_inventory,
            parallel=True,
            concurrency=5,
        ),
        # Covariate time series: daily price/promotion/rating from Xiyouzhaoci.
        # Runs in Stage 1 (independent of campaign data) so the series is ready
        # before run_causal_analysis annotates each change event with covariate context.
        EnrichStep(
            name="fetch_covariates",
            extractor_fn=_enrich_covariates,
            parallel=True,
            concurrency=3,
            enabled=config.get("enable_xiyou", True),
        ),

        # ── Stage 2: campaign structure (fetch account-level once, filter per ASIN) ──
        EnrichStep(
            name="fetch_campaigns",
            extractor_fn=_enrich_campaigns,
            parallel=True,
            concurrency=5,
        ),

        # ── Stage 3: performance + keywords (depend on campaign_ids from stage 2) ──
        EnrichStep(
            name="fetch_performance",
            extractor_fn=_enrich_performance,
            parallel=True,
            concurrency=5,
        ),
        EnrichStep(
            name="fetch_keywords",
            extractor_fn=_enrich_keywords,
            parallel=True,
            concurrency=5,
        ),

        # ── Stage 4: keyword-level + placement + competitor prices (parallel) ─
        EnrichStep(
            name="fetch_keyword_performance",
            extractor_fn=_enrich_keyword_performance,
            parallel=True,
            concurrency=5,
        ),
        EnrichStep(
            name="fetch_placement",
            extractor_fn=_enrich_placement,
            parallel=True,
            concurrency=5,
        ),
        # Depends on fetch_catalog (brand name for keyword filtering).
        # Runs here (after Stage 1) so brand is already in item.
        EnrichStep(
            name="fetch_competitor_prices",
            extractor_fn=_enrich_competitor_prices,
            parallel=True,
            concurrency=2,   # each call spawns up to 15 sub-requests; keep low
            enabled=config.get("enable_xiyou", True),
        ),

        # ── Stage 5a: temporal — daily performance + change history ───────────
        EnrichStep(
            name="fetch_change_history",
            extractor_fn=_enrich_change_history,
            parallel=True,
            concurrency=5,
        ),

        # ── Stage 5b: LP budget optimisation (pure Python, OR-Tools) ─────────
        ProcessStep(
            name="optimize_budget",
            fn=_optimize_budget,
            compute_target=ComputeTarget.PURE_PYTHON,
        ),

        # ── Stage 5c: causal analysis (window attribution + ITS/CI/DML) ──────
        # Absorbs the old correlate_changes step: produces change_attributions
        # with ITS/CausalImpact/DML results embedded per event.
        # Runs before stage 6 so statistical evidence reaches the LLM prompt
        # even when rank/trends data is not yet available.
        ProcessStep(
            name="run_causal_analysis",
            fn=_run_causal_analysis,
            compute_target=ComputeTarget.PURE_PYTHON,
            enabled=config.get("enable_causal_analysis", True),
        ),

        # ── Stage 6: Xiyouzhaoci keyword signals ─────────────────────────────
        EnrichStep(
            name="fetch_xiyou_rankings",
            extractor_fn=_enrich_xiyou_rankings,
            parallel=True,
            concurrency=3,
            enabled=config.get("enable_xiyou", True),
        ),
        # Fetches natural_rank_series + market_trends in one step.
        # Keywords selected once via _select_rank_keywords; both API calls
        # (rank trends, SFR trends) run concurrently inside the enricher.
        # Requires keyword_performance (Stage 4) and lp_top_allocations (Stage 5b).
        EnrichStep(
            name="fetch_keyword_signals",
            extractor_fn=_enrich_keyword_signals,
            parallel=True,
            concurrency=2,   # each call issues 2 Xiyou requests; keep low
            enabled=config.get("enable_xiyou", True),
        ),

        # ── Stage 7a: inject pre-computed summary before LLM ─────────────────
        # Injects _summary_json (Python-exact highlights) into each item so the
        # prompt can reference pre-computed values without asking the LLM to
        # re-derive them from the full JSON. No fields are removed.
        ProcessStep(
            name="prepare_for_llm",
            fn=_prepare_for_llm,
            compute_target=ComputeTarget.PURE_PYTHON,
        ),

        # ── Stage 7b: LLM diagnostic synthesis ───────────────────────────────
        # batch_threshold=1: always use Batch API (data collection takes 30+ min,
        # so async batch adds no perceived latency; 50% cost saving on large payloads).
        ProcessStep(
            name="ad_diagnosis_llm",
            batch_threshold=1,
            prompt_template=(
                "You are a senior Amazon advertising analyst. Analyse the following enriched "
                "advertising dataset for {count} ASIN(s) and produce a structured diagnostic "
                "report strictly following the output format below.\n\n"
                "Report date: {report_date}  (use this to interpret relative dates — "
                "e.g., a change_attribution event on 2026-04-17 is 10 days ago; "
                "the last entry in natural_rank_series is today's rank.)\n\n"
                "Pre-computed highlights (authoritative — do not re-derive these values):\n"
                "{_summary_json}\n\n"
                "Full enriched data (use for keyword-level, attribution, rank-series, "
                "trend, and competitor analysis):\n{items_json}\n\n"

                # ── Output format ────────────────────────────────────────────
                "==== OUTPUT FORMAT (repeat for each ASIN) ====\n\n"

                "## ASIN: {{asin}} – Severity: 🟢 Healthy / 🟡 Warning / 🔴 Critical\n\n"

                "### Quick Metrics Snapshot\n\n"
                "The block below is the authoritative pre-computed summary. "
                "Render ALL fields as a three-column table (Field | Value | Source / How derived). "
                "Use `null` as-is — do NOT substitute guesses. "
                "Do NOT re-derive any value from the full JSON.\n\n"
                "Column definitions:\n"
                "- **Field**: exact key name from the JSON below.\n"
                "- **Value**: exact value (keep null as `—`).\n"
                "- **Source / How derived**: one short phrase explaining origin. "
                "Use the legend below; if a key is not listed, infer from context.\n\n"
                "Legend (Field → derivation):\n"
                "  title / brand / size / bullet_point_count → SP-API Catalog\n"
                "  total_available / total_inbound → SP-API FBA Inventory (unit count)\n"
                "  can_sell_days → total_available ÷ daily_sales "
                "(daily_sales from ad orders ÷ days if not supplied by caller; null = no sales data)\n"
                "  inventory_risk → can_sell_days < inventory_risk_days config (default 30 d)\n"
                "  campaign_count → count of campaigns whose name contains the ASIN\n"
                "  total_daily_budget → sum of ENABLED campaign daily budgets (Ads API)\n"
                "  bidding_strategies → distinct strategies across matched campaigns\n"
                "  total_spend / total_sales / total_orders / total_clicks → "
                "spCampaigns performance report, summed over matched campaigns × lookback days\n"
                "  account_acos → total_spend ÷ total_sales × 100\n"
                "  budget_exhaustion_pct → total_spend ÷ (total_daily_budget × days)\n"
                "  budget_likely_exhausted → budget_exhaustion_pct > 90% threshold\n"
                "  keyword_count / avg_bid / min_bid / max_bid / match_type_dist → "
                "Ads API keyword list for matched campaigns\n"
                "  kw_performance_count → rows in spSearchTerm report with ≥ min_clicks_for_cvr clicks\n"
                "  lp_summary / lp_top_allocations / lp_zero_keywords / lp_maxed_keywords → "
                "OR-Tools LP (maximise orders s.t. daily_budget; headroom_factor × daily_clicks cap)\n"
                "  ad_traffic_ratio / organic_traffic_ratio / traffic_growth_7d → "
                "Xiyouzhaoci traffic score API\n"
                "  rank_tracked_keywords / rank_series_days → "
                "Xiyouzhaoci daily organic rank trends (days with rank data for top keyword)\n"
                "  market_trends_keywords → keywords with SFR weekly trend data (Xiyouzhaoci)\n"
                "  change_attributions_count → change events that passed noise filter (Ads API history)\n"
                "  causal_consensus_sample → consensus label of first change_attribution entry "
                "(ITS + CausalImpact + DML agreement: Strong / Moderate / Weak / Confounded / Skipped)\n\n"
                "```json\n{_summary_json}\n```\n\n"
                "> **Evidence Summary**: 1-2 sentences citing the single most critical metric "
                "visible in the snapshot above "
                "(e.g., ACOS 45% vs. 30% warn threshold, budget exhausted 27/30 days, "
                "organic rank dropped from #12 → #28 over 10 days, "
                "can_sell_days=null → daily_sales not resolved). "
                "If a key field is null, call it out explicitly.\n\n"

                "### Diagnostic Findings\n\n"
                "Each bullet must include a direct data citation in *italics*.\n\n"
                "- **Budget**: [Insight] — "
                "*Source: daily_budget=$val, budget_likely_exhausted=T/F over N days*\n"
                "- **Bids vs. Competition**: [Insight] — "
                "*Source: avg_bid=$val, high_acos_keywords=[kw1(ACOS%), kw2(ACOS%)]*\n"
                "- **Placement Strategy**: [Insight] — "
                "*Source: TOS ACOS=$val (modifier=$x%, spend_share=$y%) | "
                "PP ACOS=$val (modifier=$z%, spend_share=$w%) → mismatch if any*\n"
                "- **Keywords**: [Insight] — "
                "*Source: keyword_count=$n, match_type_dist={{exact:$a%, phrase:$b%}}, "
                "high_acos_keywords=[...]*\n"
                "- **Organic & Market**: [Insight] — "
                "*Source: ad_traffic_ratio=$val, organic_rank_trend=improving/stable/declining "
                "for kw=$kw; SFR trend up/down in week YYYY-Www → demand increased/decreased*\n"
                "- **Inventory**: [Insight] — "
                "*Source: inventory_risk=T/F, can_sell_days=$d*\n"
                "- **Profitability**: [Insight] — "
                "*Source: account_acos=$val%, TACOS=$val% (if tacos available), "
                "net_profit_after_ads=$val (if cogs+price provided)*\n"
                "- **LP Budget Optimisation**: [Insight] — "
                "*Source: order_gap=$val orders left on table, "
                "lp_zero_keywords=[kw1, kw2], lp_maxed_keywords=[kw3], "
                "lp_top_allocations=[kw4: $budget_share%]*\n"
                "- **Change Attribution (past actions)**:\n"
                "  - ✅ Positive: $change_type on $date → Δ orders = +$x "
                "(causal confidence: high/med/low)\n"
                "  - ❌ Negative: $change_type on $date → Δ ACOS = +$y pp "
                "(causal confidence: high/med/low)\n"
                "  - ⚠️ Confounded: $change_type coincided with promotion/price cut → "
                "effect cannot be isolated to bid/budget\n\n"

                "### Causal Confidence Assessment\n\n"
                "For each change_attribution entry cited above:\n"
                "- **Consensus**: Strong / Moderate / Weak / Confounded / Skipped "
                "(read from the `consensus` field directly)\n"
                "- **ITS**: level_shift=$val, p=$p_val (significant if p < 0.10)\n"
                "- **Causal Impact**: point_effect=$val (actual − counterfactual)\n"
                "- **DML**: theta=$val (residualised effect after removing price/rank/SFR/competitor "
                "confounders; reliable only if r_squared ≥ 0)\n"
                "- **Note**: Use 'causally demonstrated' only when consensus = 'Strong evidence' "
                "(all 3 models agree). Use 'suggested' or 'estimated' otherwise.\n"
                "  When had_promotion=True or price_delta_window is large negative: "
                "do not attribute lift solely to the ad change — flag as partially confounded.\n"
                "  Use competitor_price_summary {{min, max, median}} time series to explain "
                "sustained ACOS/CVR shifts that correlate with competitor price moves "
                "rather than internal bid changes.\n\n"

                "### Top 5 Prioritised Actions (most impactful first)\n\n"
                "For each action use this sub-structure:\n\n"
                "> **Action #N**: [Specific action with concrete numbers, "
                "e.g., increase TOS modifier from 10% → 30%]\n"
                "> - **Rationale**: [1-2 sentences with data citations]\n"
                ">   *Evidence: placement_performance.TOS.acos=$val, spend_share=$val%*\n"
                "> - **Expected impact**: [Quantified estimate] "
                "*(assuming CVR and CTR remain stable)*\n"
                "> - **Risks / caveats**: [What to monitor; set a time-box, e.g., 7 days]\n"
                "> - **Reference change attribution**: [Cite a past change_attribution entry "
                "if a similar action was taken; include the consensus confidence level. "
                "If none exists, write 'No historical reference available.']\n\n"

                "### Account Health Summary\n\n"
                "- **Overall Health Score**: 🟢 / 🟡 / 🔴 "
                "(based on proportion of ASINs at each severity level)\n"
                "- **Biggest Win (Last 30d)**: $change_type on $date for ASIN $x → "
                "saved/earned $impact (cite change_attribution)\n"
                "- **Biggest Risk**: One sentence on the highest-severity unresolved issue "
                "across all ASINs\n"
                "- **Single Most Important Action (account-wide)**: Repeat the #1 action "
                "if it applies globally\n"
                "- **Monitoring Recommendation**: Which 1-2 metrics to track weekly\n\n"

                # ── Credibility & actionability rules ────────────────────────
                "==== MANDATORY RULES (violations degrade report quality) ====\n\n"
                "1. Every claim must be accompanied by a direct data reference "
                "(field name + value from the JSON). No assertion without citation.\n"
                "2. When recommending a bid change, provide a numerical bound "
                "(e.g., 'raise from $0.50 to $0.75') and cite a historical "
                "change_attribution entry if available.\n"
                "3. For any 'expected impact' estimate, state the assumption explicitly "
                "(e.g., 'assuming CVR and CTR remain stable').\n"
                "4. Uncertainty labelling: use 'suggested' / 'estimated' / 'may' when the "
                "effect is derived from pre/post windows without causal model agreement. "
                "Use 'demonstrated' / 'causally linked' only when consensus = 'Strong evidence'.\n"
                "5. If confounders exist (promotion, price cut, competitor move), "
                "do not attribute the outcome solely to ad actions — "
                "rewrite the conclusion to reflect partial or unclear attribution.\n"
                "6. Append a **Caveats & Data Quality** subsection at the end of each ASIN "
                "report if ANY of the following are true:\n"
                "   - placement_performance is missing or empty\n"
                "   - keyword_count < 10\n"
                "   - More than half of change_attribution entries have skipped=True "
                "for all three causal models\n"
                "   - post_window.days < 5 for the majority of attributions\n"
                "Begin the report now."
            ),
            compute_target=ComputeTarget.CLOUD_LLM,
        ),

        # ── Stage 8: write report to .md and set report_file_path ────────────
        # FeishuCallback.on_complete picks up report_file_path and sends it as
        # a file attachment. item["response"] is set to a short preview so the
        # card branch shows a summary without creating a duplicate attachment.
        ProcessStep(
            name="export_report",
            fn=_export_report,
            compute_target=ComputeTarget.PURE_PYTHON,
        ),
    ]

    if config.get("no_llm", False):
        steps = [s for s in steps if s.name not in (
            "prepare_for_llm", "ad_diagnosis_llm", "export_report"
        )]

    return Workflow(name="ad_diagnosis", steps=steps)
