from __future__ import annotations
from pydantic import BaseModel, Field
from typing import List, Optional
from .product import Product

class CompetitorEntry(BaseModel):
    """
    Detailed entry for a specific competitor within a niche analysis.
    """
    product: Product
    market_share_estimate: Optional[float] = Field(None, description="Estimated share of search results or sales")
    competitive_advantage: str = Field(..., description="Key reason this product sells well compared to others")
    weaknesses: List[str] = Field(..., description="Vulnerabilities that a new entrant could exploit")

class MarketAnalysisReport(BaseModel):
    """
    High-level intelligence report generated by the Researcher Agent.
    """
    keyword: str = Field(..., description="The primary search term analyzed")
    category_node_id: Optional[str] = Field(None, description="The Browse Node ID used for sales calculation")
    avg_price: float = Field(..., description="Mean price point across the top search results")
    avg_rating: float = Field(..., description="Average rating of the niche")
    total_estimated_sales: int = Field(..., description="Total unit sales estimate for the niche (monthly)")
    confidence_score: Optional[float] = Field(None, description="Model confidence based on R^2 of the category estimator")
    top_competitors: List[CompetitorEntry] = Field(..., description="Analysis of the top-performing competitor listings")
    entry_barrier_score: float = Field(..., description="Scale from 0.0 to 10.0 (10.0 being extremely hard to enter)")
    swot_analysis: dict = Field(..., description="Strengths, Weaknesses, Opportunities, and Threats")
    summary: str = Field(..., description="Final professional recommendation for entering this niche")
